### PR TITLE
fix: update dependencies and fix crashes

### PR DESCRIPTION
**Pull request by wolf31o2**
Downgrade a pile of stuff to get us stable, again. I'll do more updates in subsequent PRs.

### CODE REVIEW

**Comment by reqlez** [comment]
Sir, how is this "downgrade"  ... I remember that newer Axios had issues, did you test it, just confirming...
image

**Comment by wolf31o2** [comment]
I sent you a screenshot when I submitted it.

**Comment by wolf31o2** [comment]
It's a downgrade because I reverted the piles of blind updates you did and only updated axios and fixed that.





You can test locally, which you should be doing on any pull request. Run `bash dev.sh` and visit `http://localhost:3001` (you will need a valid VM API token in `.env`)

**Comment by wolf31o2** [comment]
I removed `bulma` completely from the frontend. It wasn't in use.

`bash dev.sh` afterwards:
image

**Comment by wolf31o2** [comment]
You can also `git remote add blinklabs git@github.com:blinklabs-io/tosidrop-vm-frontend.git` to add a remote for our fork to your local checkout. From there, you can `git fetch blinklabs` to update your local metadata and `git checkout <branch>` from any of our PRs to test for yourself.

**Comment by reqlez** [comment]
> You can also `git remote add blinklabs git@github.com:blinklabs-io/tosidrop-vm-frontend.git` to add a remote for our fork to your local checkout. From there, you can `git fetch blinklabs` to update your local metadata and `git checkout <branch>` from any of our PRs to test for yourself.

No, I trust you, I just raised the question because I tried upgrading that dam Axios last time, and got nothing but errors, but if you got it to work, that's great!

Thanks for the PR and working on this, good sir :)

**Review by reqlez — APPROVED** [review]

**Pull request merged**
