### PR TITLE
feat: minswap prices

### PR DESCRIPTION
**Pull request by wolf31o2**
Before:
image (4)

After:
image (5)

This replaces #368 

Signed-off-by: Chris Gianelloni <cgianelloni@cloudstruct.net>

### CODE REVIEW

**Comment by aryelciu001** [comment]
nice one

**Comment by reqlez** [comment]
Thanks Chris!  @aryelciu001 what about having a "total" price as well? for each token?

**Comment by wolf31o2** [comment]
You want me to math? I can math. I'm truncating at 8 digits, so I would need to keep the complete price and truncate somewhere else.

**Comment by wolf31o2** [comment]
I added totals.
image

**Comment by reqlez** [comment]
> I added totals. image

Okay that is even more awesome!    @aryelciu001 wut u think RE UI?  does this info maybe better off being on mouseover or something?  I think every box showing price is kinda... i dunno, weird in a way. I was thinking maybe mouseover is the way, if some people really care about prices of tokens they are claiming they can just mouse over the token to check?

**Comment by aryelciu001** [comment]
We can merge it. I will polish the UI. Thanks! @wolf31o2

**Review by aryelciu001 — APPROVED** [review]

**Pull request merged**
